# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44bb066680270574ae53ee4838cba4ec86e6bb32cbaccd8b9c5be8ee81026f745fb854497122ceeedad691437f8559f8ac10a09388a28f109ee7f0023245ffbf

test:
  secret_key_base: 0e5dd38e73798e22b95587fac87a4eb8eeb971e95227b2fd57a7bdaa1b0cb457fd7844cd5871b76110bd8170115c723e1e72b6236e2bb245068580e0570bbffb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
